name: TRMNL Serverless Hack

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Puppeteer e ImageMagick
        run: |
          npm install puppeteer
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Gerar HTML e Screenshot (PNG)
        run: node build.mjs

      - name: Converter para BMP (Preto e Branco)
        run: convert screen.png -monochrome -colors 2 -alpha off -depth 1 -strip bmp:image.bmp

      - name: Gerar API JSON
        run: |
          mkdir -p api
          cat << 'EOF' > api/display
          {
            "status": 0,
            "image_url": "https://whysoseriusbro.github.io/meu-clima/image.bmp",
            "filename": "image.bmp",
            "refresh_rate": 3600,
            "reset_firmware": false,
            "update_firmware": false,
            "firmware_url": null,
            "special_function": "sleep"
          }
          EOF

      - name: Fazer Commit e Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html screen.png image.bmp api/display
          git commit -m "chore: atualiza imagem TRMNL" || echo "Sem mudanças para commitar"
          git push
